apiVersion: v1
kind: Service
metadata:
  name: {{ include "abs.fullname" . }}-backend
  labels:
    {{- include "abs.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "abs.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 8000
      targetPort: 8000
